export default {
  ADD_COMMAND: 'ADD_COMMAND',
  DEL_COMMAND: 'DEL_COMMAND',
  SAVE_COMMANDS: 'SAVE_COMMANDS',
  ACTION: 'ACTION',
  COMMAND: 'COMMAND',
  UPDATE_COMMAND: 'UPDATE_COMMAND',
  LOAD_PACKAGE: 'LOAD_PACKAGE',
  CHANGE_CONFIG: 'CHANGE_CONFIG',
  SAVE_CONFIG: 'SAVE_CONFIG' };
